[config]
version_check = false
caching = true

expr_prefix = "{{"
expr_postfix = "}}"

block_prefix = "<*"
block_postfix = "*>"

[templates.preview]
input_path = '~/.config/matugen/templates/preview.html'
output_path = '~/.config/matugen/preview.html'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/core/colors.conf'

[templates.hyprtoolkit]
input_path = '~/.config/matugen/templates/hyprtoolkit.conf'
output_path = '~/.config/hypr/hyprtoolkit.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.lazygit]
input_path = '~/.config/matugen/templates/lazygit.yml'
output_path = '~/.config/lazygit/config.yml'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client --reload-css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
