gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a96249"
      - "bold"
    inactiveBorderColor:
      - "#46120d"
    searchingActiveBorderColor:
      - "#a96249"
      - "bold"
    optionsTextColor:
      - "#f2f4f8"
    selectedLineBgColor:
      - "#2a2a2a"
    cherryPickedCommitFgColor:
      - "#a96249"
    cherryPickedCommitBgColor:
      - "#be95ff"
    markedBaseCommitFgColor:
      - "#a96249"
    markedBaseCommitBgColor:
      - "#08bdba"
    unstagedChangesColor:
      - "#ee5396"
    defaultFgColor:
      - "#f2f4f8"
